In [1]:
import rastereasy

# Dempster-Shafer fusion for 2 hypotheses

It is possible to fuse belief masses issued from images for two hypotheses A and B.
For this, we assume that each image is composed of 3 spectral bands : 
- 1st band : belief mass $m(A)$ for hypothesis $A$
- 2nd band : belief mass $m(B)$ for hypothesis $B$
- 3rd band : belief mass $m(A \cup B)$ for hypothesis $A \cup B$ (uncertainty)

For consistent mass functions, the sum along bands must be $1$ for each pixel of each source

## 1) Create 5 toy images

In [2]:
# 1. Read image (just to have meta informations)
name_im='./data/demo/sentinel.tif'
image=rastereasy.Geoimage(name_im)
# 2. Create a 3 band image consistent with mass functions (i.e. positive and  sum to 1)
import numpy as np
raw = np.random.rand(image.shape[0], image.shape[1], 3)
# 3. Normalize  mass functions such that m(A) + m(B) + m(A∪B) = 1 in each pixel
mass_functions = raw / np.sum(raw, axis=2, keepdims=True)
print(mass_functions.shape)
# 4. Upload the table 
mass_function1 = image.upload_image(mass_functions,channel_first=False)
# 5 verify that the sum is 1 along bands
print(mass_function1.sum(axis='band'))

## Repeat this operation 5 times to create 5 sources
raw = np.random.rand(image.shape[0], image.shape[1], 3)
mass_functions = raw / np.sum(raw, axis=2, keepdims=True)
mass_function2 = image.upload_image(mass_functions,channel_first=False)

raw = np.random.rand(image.shape[0], image.shape[1], 3)
mass_functions = raw / np.sum(raw, axis=2, keepdims=True)
mass_function3 = image.upload_image(mass_functions,channel_first=False)

raw = np.random.rand(image.shape[0], image.shape[1], 3)
mass_functions = raw / np.sum(raw, axis=2, keepdims=True)
mass_function4 = image.upload_image(mass_functions,channel_first=False)

raw = np.random.rand(image.shape[0], image.shape[1], 3)
mass_functions = raw / np.sum(raw, axis=2, keepdims=True)
mass_function5 = image.upload_image(mass_functions,channel_first=False)


(1000, 1000, 3)
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [3]:
mass_function1.image

array([[[0.49920933, 0.18496414, 0.316482  , ..., 0.37680265,
         0.33095465, 0.15351193],
        [0.14771654, 0.61066236, 0.35155943, ..., 0.3178492 ,
         0.13321229, 0.71319421],
        [0.12254127, 0.18470702, 0.63332031, ..., 0.35234872,
         0.32876161, 0.01011653],
        ...,
        [0.36147071, 0.60313576, 0.20814396, ..., 0.49161931,
         0.26376989, 0.43454605],
        [0.2294948 , 0.16085746, 0.4035564 , ..., 0.20113919,
         0.60407758, 0.45760474],
        [0.38214895, 0.32976356, 0.36537958, ..., 0.25041385,
         0.21898076, 0.37783871]],

       [[0.01941518, 0.42965461, 0.42694872, ..., 0.25142228,
         0.5496116 , 0.43374666],
        [0.82652542, 0.14038671, 0.21909285, ..., 0.41605606,
         0.42354583, 0.27459863],
        [0.16113139, 0.64475432, 0.07696209, ..., 0.44046052,
         0.43276968, 0.42984358],
        ...,
        [0.33496399, 0.12559128, 0.29081864, ..., 0.27476165,
         0.01851573, 0.4632653 ],
        [0.3

## 2) Perform the fusion

### 1) With function `fuse_dempster_shafer_2` of class `Geoimage`

In [4]:
help(mass_function1.fuse_dempster_shafer_2)

Help on method fuse_dempster_shafer_2 in module rastereasy_dev:

fuse_dempster_shafer_2(*images) method of rastereasy_dev.Geoimage instance
    Fuse the 3 band image (associated with mass functions) from multiple
    sources using Dempster-Shafer theory with two hypotheses: A and B.
    
    Parameters
    ----------
    *images : Geoimage
        Each input is a 3-band Geoimage.
    
        - Band 1: mass function m(A)
    
        - Band 2: mass function m(B)
    
        - Band 3: mass function m(A ∪ B)
    
    Returns
    -------
    Geoimage
        A new Geoimage with 3 bands containing the fused mass functions:
        m(A), m(B), and m(A ∪ B).
    Geoimage
        A new Geoimage with 1 band containing the conflict values.
    
    Examples
    --------
    >>> fused, conflict = im1.fuse_dempster_shafer_2(im2)
    >>> fused, conflict = im1.fuse_dempster_shafer_2(im1, im2, im3, im4)



In [5]:
fusion, conflict = mass_function2.fuse_dempster_shafer_2(mass_function5,mass_function4,mass_function1,mass_function3)

### 2) With function `fuse_dempster_shafer_2hypotheses` of class `InferenceTools`

In [6]:
help(rastereasy.InferenceTools.fuse_dempster_shafer_2hypotheses)

Help on function fuse_dempster_shafer_2hypotheses in module rastereasy_dev:

fuse_dempster_shafer_2hypotheses(*images)
    Fuse mass functions from multiple sources using Dempster-Shafer theory
    with two hypotheses: A and B.
    
    Parameters
    ----------
    *images : Geoimage
        Each input is a 3-band Geoimage.
    
        - Band 1: mass function m(A)
    
        - Band 2: mass function m(B)
    
        - Band 3: mass function m(A ∪ B)
    
    Returns
    -------
    Geoimage
        A new Geoimage with 3 bands containing the fused mass functions:
        m(A), m(B), and m(A ∪ B).
    Geoimage
        A new Geoimage with 1 band containing the conflict values.
    
    Examples
    --------
    >>> fused, conflict = fuse_dempster_shafer_2hypotheses(im1, im2, im3)
    >>> fused, conflict = fuse_dempster_shafer_2hypotheses(im1, im2, im3, im4)
    >>> fused, conflict = fuse_dempster_shafer_2hypotheses(im1, im2)



In [7]:
fusion, conflict = rastereasy.InferenceTools.fuse_dempster_shafer_2hypotheses(
    mass_function5,
    mass_function4,
    mass_function3,
    mass_function2,
    mass_function1)

Verify that the fused masses sum to $1$

In [8]:
fusion.sum(axis='band')

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], shape=(1000, 1000))